### ISSUE TITLE
Boto issue on my RHEL laptop - any ideas?

### ISSUE THREAD

**Issue by dudash** [jaredhocutt/openshift-provision#9]
Running into this on my RHEL laptop - I can run this exact command using the same config from my other RHEL EC2 instance... not sure what's different.

```[jdudash@lennylinux jhocutt-ocpprovision]$ docker run -it --rm --volume $(pwd):/app:z --env-file vars/aws.env quay.io/jhocutt/openshift-provision ansible-playbook playbooks/aws/provision.yml -e @vars/aws.yml -v
Using /app/ansible.cfg as config file
 [WARNING]:  * Failed to parse /app/inventory/inventory.aws_ec2.yml with aws_ec2 plugin: Failed to describe instances: Could not connect to the endpoint URL: "https://ec2.us-east-2.amazonaws.com/"

 [WARNING]:  * Failed to parse /app/inventory/inventory.aws_ec2.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory

 [WARNING]: Unable to parse /app/inventory/inventory.aws_ec2.yml as an inventory source


PLAY [localhost] **********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************************************************
Wednesday 15 August 2018  14:16:55 +0000 (0:00:00.129)       0:00:00.129 ****** 
ok: [localhost]

TASK [provision_aws : Create EC2 key pair] ********************************************************************************************************************************************************************************************
Wednesday 15 August 2018  14:16:56 +0000 (0:00:00.668)       0:00:00.797 ****** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ec2.us-east-2.amazonaws.com/"
fatal: [localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE


MODULE_STDERR:

Traceback (most recent call last):
  File "/tmp/ansible_7f52onyy/ansible_module_ec2_key.py", line 269, in <module>
    main()
  File "/tmp/ansible_7f52onyy/ansible_module_ec2_key.py", line 265, in main
    create_key_pair(module, ec2_client, name, key_material, force)
  File "/tmp/ansible_7f52onyy/ansible_module_ec2_key.py", line 186, in create_key_pair
    key = find_key_pair(module, ec2_client, name)
  File "/tmp/ansible_7f52onyy/ansible_module_ec2_key.py", line 176, in find_key_pair
    key = ec2_client.describe_key_pairs(KeyNames=[name])['KeyPairs'][0]
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 148, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 177, in _send_request
    success_response, exception):
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 273, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ec2.us-east-2.amazonaws.com/"

```

**Comment by jaredhocutt** [comment]
I know we spoke in person about this one and it seemed to be related to your DNS resolution on your RHEL laptop.

Have you fixed the DNS issue to see if this issue went away?

**Comment by dudash** [comment]
Oh yeah. This was totally my issue. Meant to close it.
Thanks!
